In [23]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [24]:
data=pd.read_csv('student_performance_updated_1000.csv')

In [25]:
df=pd.DataFrame(data)

In [26]:
df.head()

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  960 non-null    float64
 1   Name                       966 non-null    object
 2   Gender                     952 non-null    object
 3   AttendanceRate             960 non-null    float64
 4   StudyHoursPerWeek          950 non-null    float64
 5   PreviousGrade              967 non-null    float64
 6   ExtracurricularActivities  957 non-null    float64
 7   ParentalSupport            978 non-null    object
 8   FinalGrade                 960 non-null    float64
 9   Study Hours                976 non-null    float64
 10  Attendance (%)             959 non-null    float64
 11  Online Classes Taken       975 non-null    object
dtypes: float64(8), object(4)
memory usage: 93.9+ KB

In [28]:
df.drop(['StudentID','Name'],axis=1,inplace=True)

In [30]:
df[['StudyHoursPerWeek','Study Hours']].corr()

                   StudyHoursPerWeek  Study Hours
StudyHoursPerWeek           1.000000    -0.024963
Study Hours                -0.024963     1.000000

In [31]:
df[['AttendanceRate','Attendance (%)']].corr()

                AttendanceRate  Attendance (%)
AttendanceRate        1.000000        0.012636
Attendance (%)        0.012636        1.000000

In [32]:
# Numerical misssing value

num_cols=df.select_dtypes(include='number').columns

df[num_cols]=df[num_cols].fillna(df[num_cols].median())

In [37]:
# Categorical missing value

cat_cols=df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col]=df[col].fillna(df[col].mode()[0])

C:\Users\skmor\AppData\Local\Temp\ipykernel_13636\4018811709.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col]=df[col].fillna(df[col].mode()[0])

In [38]:
df.isnull().sum()

Gender                       0
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
ParentalSupport              0
FinalGrade                   0
Study Hours                  0
Attendance (%)               0
Online Classes Taken         0
dtype: int64

In [39]:
df['FinalGrade'].value_counts()

FinalGrade
80.0    142
72.0    110
78.0    104
92.0     97
85.0     97
90.0     96
62.0     95
87.0     94
68.0     88
88.0     77
Name: count, dtype: int64

In [45]:
# Select the features

X=df.drop(['FinalGrade'],axis=1)

In [46]:
# Apply one-hot encoding
X=pd.get_dummies(X,drop_first=True)

In [47]:
# Target column
Y=df['FinalGrade']

In [43]:
X

,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,Study Hours,Attendance (%),Online Classes Taken
0,Male,85.0,15.0,78.0,1.0,High,4.8,59.0,False
1,Female,90.0,20.0,85.0,2.0,Medium,2.2,70.0,True
2,Male,78.0,10.0,65.0,0.0,Low,4.6,92.0,False
3,Male,92.0,25.0,90.0,3.0,High,2.9,96.0,False
4,Female,88.0,18.0,82.0,2.0,Medium,4.1,97.0,True
...,...,...,...,...,...,...,...,...,...
995,Male,85.0,20.0,78.0,1.0,High,0.8,80.0,True
996,Female,91.0,18.0,86.0,0.0,High,3.9,80.0,True
997,Male,85.0,8.0,82.0,2.0,Low,0.4,54.0,False
998,Male,88.0,17.0,60.0,2.0,High,0.9,53.0,True
999,Female,88.0,10.0,90.0,1.0,Medium,2.4,94.0,True

In [48]:
Y

0      80.0
1      87.0
2      68.0
3      92.0
4      85.0
       ...
995    72.0
996    90.0
997    68.0
998    85.0
999    80.0
Name: FinalGrade, Length: 1000, dtype: float64