In [121]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [122]:
data=pd.read_csv('student_performance_updated_1000.csv')

In [123]:
df=pd.DataFrame(data)

In [124]:
df.head()

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  960 non-null    float64
 1   Name                       966 non-null    object
 2   Gender                     952 non-null    object
 3   AttendanceRate             960 non-null    float64
 4   StudyHoursPerWeek          950 non-null    float64
 5   PreviousGrade              967 non-null    float64
 6   ExtracurricularActivities  957 non-null    float64
 7   ParentalSupport            978 non-null    object
 8   FinalGrade                 960 non-null    float64
 9   Study Hours                976 non-null    float64
 10  Attendance (%)             959 non-null    float64
 11  Online Classes Taken       975 non-null    object
dtypes: float64(8), object(4)
memory usage: 93.9+ KB

In [126]:
df.describe()

,StudentID,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,FinalGrade,Study Hours,Attendance (%)
count,960.000000,960.000000,950.000000,967.000000,957.000000,960.000000,976.000000,959.000000
mean,5416.019792,85.510417,17.630526,77.598759,1.520376,80.030208,2.406967,77.248175
std,2653.748319,7.332125,6.272132,10.006640,1.046439,9.493652,1.620267,19.298148
min,1.000000,70.000000,8.000000,60.000000,0.000000,62.000000,-5.000000,50.000000
25%,3113.500000,82.000000,12.000000,70.000000,1.000000,72.000000,1.200000,63.000000
50%,5396.500000,88.000000,18.000000,78.000000,1.000000,80.000000,2.500000,76.000000
75%,7754.750000,91.000000,22.000000,86.000000,2.000000,88.000000,3.700000,89.000000
max,9998.000000,95.000000,30.000000,90.000000,3.000000,92.000000,5.000000,200.000000

In [127]:
# Numerical misssing value

num_cols=df.select_dtypes(include='number').columns

df[num_cols]=df[num_cols].fillna(df[num_cols].median())

In [128]:
# Categorical missing value

cat_cols=df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col]=df[col].fillna(df[col].mode()[0])

C:\Users\skmor\AppData\Local\Temp\ipykernel_13636\4018811709.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col]=df[col].fillna(df[col].mode()[0])

In [129]:
df.isnull().sum()

StudentID                    0
Name                         0
Gender                       0
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
ParentalSupport              0
FinalGrade                   0
Study Hours                  0
Attendance (%)               0
Online Classes Taken         0
dtype: int64

In [130]:
# Remove unnecessary columns

df=df.drop(['StudentID','Name'],axis=1)

In [131]:
df.head()

,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,Female,88.0,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True

In [139]:
# Check duplicate

df[['StudyHoursPerWeek','Study Hours']].corr()

                   StudyHoursPerWeek  Study Hours
StudyHoursPerWeek           1.000000    -0.024034
Study Hours                -0.024034     1.000000

In [140]:
df[['AttendanceRate','Attendance (%)']].corr()

                AttendanceRate  Attendance (%)
AttendanceRate        1.000000        0.011297
Attendance (%)        0.011297        1.000000

In [132]:
# Select the features

X=df.drop(['FinalGrade'],axis=1)

In [133]:
# Apply one-hot encoding
X=pd.get_dummies(X,drop_first=True)

In [134]:
# Target column
Y=df['FinalGrade']

In [135]:
X

,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,Study Hours,Attendance (%),Online Classes Taken,Gender_Male,ParentalSupport_Low,ParentalSupport_Medium
0,85.0,15.0,78.0,1.0,4.8,59.0,False,True,False,False
1,90.0,20.0,85.0,2.0,2.2,70.0,True,False,False,True
2,78.0,10.0,65.0,0.0,4.6,92.0,False,True,True,False
3,92.0,25.0,90.0,3.0,2.9,96.0,False,True,False,False
4,88.0,18.0,82.0,2.0,4.1,97.0,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...
995,85.0,20.0,78.0,1.0,0.8,80.0,True,True,False,False
996,91.0,18.0,86.0,0.0,3.9,80.0,True,False,False,False
997,85.0,8.0,82.0,2.0,0.4,54.0,False,True,True,False
998,88.0,17.0,60.0,2.0,0.9,53.0,True,True,False,False
999,88.0,10.0,90.0,1.0,2.4,94.0,True,False,False,True

In [136]:
Y

0      80.0
1      87.0
2      68.0
3      92.0
4      85.0
       ...
995    72.0
996    90.0
997    68.0
998    85.0
999    80.0
Name: FinalGrade, Length: 1000, dtype: float64

In [137]:
### models